<?php
/**
 * VersamentoApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mentor.ApiRest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * VersamentoApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VersamentoApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation versamentoGet
     *
     * @param  string $codice_cliente codice_cliente (required)
     * @param  string $data_inizio data_inizio (optional)
     * @param  string $data_fine data_fine (optional)
     * @param  string $id_regolare id_regolare (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Versamento[]
     */
    public function versamentoGet($codice_cliente, $data_inizio = null, $data_fine = null, $id_regolare = null)
    {
        list($response) = $this->versamentoGetWithHttpInfo($codice_cliente, $data_inizio, $data_fine, $id_regolare);
        return $response;
    }

    /**
     * Operation versamentoGetWithHttpInfo
     *
     * @param  string $codice_cliente (required)
     * @param  string $data_inizio (optional)
     * @param  string $data_fine (optional)
     * @param  string $id_regolare (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Versamento[], HTTP status code, HTTP response headers (array of strings)
     */
    public function versamentoGetWithHttpInfo($codice_cliente, $data_inizio = null, $data_fine = null, $id_regolare = null)
    {
        $returnType = '\Swagger\Client\Model\Versamento[]';
        $request = $this->versamentoGetRequest($codice_cliente, $data_inizio, $data_fine, $id_regolare);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Versamento[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation versamentoGetAsync
     *
     * 
     *
     * @param  string $codice_cliente (required)
     * @param  string $data_inizio (optional)
     * @param  string $data_fine (optional)
     * @param  string $id_regolare (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function versamentoGetAsync($codice_cliente, $data_inizio = null, $data_fine = null, $id_regolare = null)
    {
        return $this->versamentoGetAsyncWithHttpInfo($codice_cliente, $data_inizio, $data_fine, $id_regolare)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation versamentoGetAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $codice_cliente (required)
     * @param  string $data_inizio (optional)
     * @param  string $data_fine (optional)
     * @param  string $id_regolare (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function versamentoGetAsyncWithHttpInfo($codice_cliente, $data_inizio = null, $data_fine = null, $id_regolare = null)
    {
        $returnType = '\Swagger\Client\Model\Versamento[]';
        $request = $this->versamentoGetRequest($codice_cliente, $data_inizio, $data_fine, $id_regolare);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'versamentoGet'
     *
     * @param  string $codice_cliente (required)
     * @param  string $data_inizio (optional)
     * @param  string $data_fine (optional)
     * @param  string $id_regolare (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function versamentoGetRequest($codice_cliente, $data_inizio = null, $data_fine = null, $id_regolare = null)
    {
        // verify the required parameter 'codice_cliente' is set
        if ($codice_cliente === null || (is_array($codice_cliente) && count($codice_cliente) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $codice_cliente when calling versamentoGet'
            );
        }

        $resourcePath = '/v1/api/Versamento/Get';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($codice_cliente !== null) {
            $queryParams['CodiceCliente'] = ObjectSerializer::toQueryValue($codice_cliente);
        }
        // query params
        if ($data_inizio !== null) {
            $queryParams['DataInizio'] = ObjectSerializer::toQueryValue($data_inizio);
        }
        // query params
        if ($data_fine !== null) {
            $queryParams['DataFine'] = ObjectSerializer::toQueryValue($data_fine);
        }
        // query params
        if ($id_regolare !== null) {
            $queryParams['id_regolare'] = ObjectSerializer::toQueryValue($id_regolare);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation versamentoInsertVersamento
     *
     * @param  \Swagger\Client\Model\Versamento[] $raw_string raw_string (required)
     * @param  string $ambiente ambiente (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Versamento[]
     */
    public function versamentoInsertVersamento($raw_string, $ambiente = null)
    {
        list($response) = $this->versamentoInsertVersamentoWithHttpInfo($raw_string, $ambiente);
        return $response;
    }

    /**
     * Operation versamentoInsertVersamentoWithHttpInfo
     *
     * @param  \Swagger\Client\Model\Versamento[] $raw_string (required)
     * @param  string $ambiente (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Versamento[], HTTP status code, HTTP response headers (array of strings)
     */
    public function versamentoInsertVersamentoWithHttpInfo($raw_string, $ambiente = null)
    {
        $returnType = '\Swagger\Client\Model\Versamento[]';
        $request = $this->versamentoInsertVersamentoRequest($raw_string, $ambiente);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Versamento[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation versamentoInsertVersamentoAsync
     *
     * 
     *
     * @param  \Swagger\Client\Model\Versamento[] $raw_string (required)
     * @param  string $ambiente (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function versamentoInsertVersamentoAsync($raw_string, $ambiente = null)
    {
        return $this->versamentoInsertVersamentoAsyncWithHttpInfo($raw_string, $ambiente)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation versamentoInsertVersamentoAsyncWithHttpInfo
     *
     * 
     *
     * @param  \Swagger\Client\Model\Versamento[] $raw_string (required)
     * @param  string $ambiente (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function versamentoInsertVersamentoAsyncWithHttpInfo($raw_string, $ambiente = null)
    {
        $returnType = '\Swagger\Client\Model\Versamento[]';
        $request = $this->versamentoInsertVersamentoRequest($raw_string, $ambiente);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'versamentoInsertVersamento'
     *
     * @param  \Swagger\Client\Model\Versamento[] $raw_string (required)
     * @param  string $ambiente (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function versamentoInsertVersamentoRequest($raw_string, $ambiente = null)
    {
        // verify the required parameter 'raw_string' is set
        if ($raw_string === null || (is_array($raw_string) && count($raw_string) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $raw_string when calling versamentoInsertVersamento'
            );
        }

        $resourcePath = '/v1/api/Versamento/InsertVersamento';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($ambiente !== null) {
            $queryParams['Ambiente'] = ObjectSerializer::toQueryValue($ambiente);
        }


        // body params
        $_tempBody = null;
        if (isset($raw_string)) {
            $_tempBody = $raw_string;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml'],
                ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation versamentoUpdateAttivita
     *
     * @param  \Swagger\Client\Model\Versamento[] $raw_string raw_string (required)
     * @param  string $ambiente ambiente (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Versamento[]
     */
    public function versamentoUpdateAttivita($raw_string, $ambiente = null)
    {
        list($response) = $this->versamentoUpdateAttivitaWithHttpInfo($raw_string, $ambiente);
        return $response;
    }

    /**
     * Operation versamentoUpdateAttivitaWithHttpInfo
     *
     * @param  \Swagger\Client\Model\Versamento[] $raw_string (required)
     * @param  string $ambiente (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Versamento[], HTTP status code, HTTP response headers (array of strings)
     */
    public function versamentoUpdateAttivitaWithHttpInfo($raw_string, $ambiente = null)
    {
        $returnType = '\Swagger\Client\Model\Versamento[]';
        $request = $this->versamentoUpdateAttivitaRequest($raw_string, $ambiente);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Versamento[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation versamentoUpdateAttivitaAsync
     *
     * 
     *
     * @param  \Swagger\Client\Model\Versamento[] $raw_string (required)
     * @param  string $ambiente (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function versamentoUpdateAttivitaAsync($raw_string, $ambiente = null)
    {
        return $this->versamentoUpdateAttivitaAsyncWithHttpInfo($raw_string, $ambiente)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation versamentoUpdateAttivitaAsyncWithHttpInfo
     *
     * 
     *
     * @param  \Swagger\Client\Model\Versamento[] $raw_string (required)
     * @param  string $ambiente (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function versamentoUpdateAttivitaAsyncWithHttpInfo($raw_string, $ambiente = null)
    {
        $returnType = '\Swagger\Client\Model\Versamento[]';
        $request = $this->versamentoUpdateAttivitaRequest($raw_string, $ambiente);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'versamentoUpdateAttivita'
     *
     * @param  \Swagger\Client\Model\Versamento[] $raw_string (required)
     * @param  string $ambiente (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function versamentoUpdateAttivitaRequest($raw_string, $ambiente = null)
    {
        // verify the required parameter 'raw_string' is set
        if ($raw_string === null || (is_array($raw_string) && count($raw_string) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $raw_string when calling versamentoUpdateAttivita'
            );
        }

        $resourcePath = '/v1/api/Versamento/UpdateAttivita';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($ambiente !== null) {
            $queryParams['Ambiente'] = ObjectSerializer::toQueryValue($ambiente);
        }


        // body params
        $_tempBody = null;
        if (isset($raw_string)) {
            $_tempBody = $raw_string;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml'],
                ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
