<?php
/**
 * AdozioniTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mentor.ApiRest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AdozioniTest Class Doc Comment
 *
 * @category    Class
 * @description Adozioni
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdozioniTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Adozioni"
     */
    public function testAdozioni()
    {
    }

    /**
     * Test attribute "id_adozione"
     */
    public function testPropertyIdAdozione()
    {
    }

    /**
     * Test attribute "codice"
     */
    public function testPropertyCodice()
    {
    }

    /**
     * Test attribute "nome"
     */
    public function testPropertyNome()
    {
    }

    /**
     * Test attribute "cognome"
     */
    public function testPropertyCognome()
    {
    }

    /**
     * Test attribute "sesso"
     */
    public function testPropertySesso()
    {
    }

    /**
     * Test attribute "data_nascita"
     */
    public function testPropertyDataNascita()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "url_foto"
     */
    public function testPropertyUrlFoto()
    {
    }

    /**
     * Test attribute "nazione"
     */
    public function testPropertyNazione()
    {
    }

    /**
     * Test attribute "programma"
     */
    public function testPropertyProgramma()
    {
    }
}
