<?php
/**
 * AttivitaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mentor.ApiRest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AttivitaTest Class Doc Comment
 *
 * @category    Class
 * @description Attivita
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AttivitaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Attivita"
     */
    public function testAttivita()
    {
    }

    /**
     * Test attribute "id_attivita"
     */
    public function testPropertyIdAttivita()
    {
    }

    /**
     * Test attribute "id_regolare"
     */
    public function testPropertyIdRegolare()
    {
    }

    /**
     * Test attribute "id_versamenti"
     */
    public function testPropertyIdVersamenti()
    {
    }

    /**
     * Test attribute "codice_donatore"
     */
    public function testPropertyCodiceDonatore()
    {
    }

    /**
     * Test attribute "campagna"
     */
    public function testPropertyCampagna()
    {
    }

    /**
     * Test attribute "canale"
     */
    public function testPropertyCanale()
    {
    }

    /**
     * Test attribute "pagamento"
     */
    public function testPropertyPagamento()
    {
    }

    /**
     * Test attribute "bambino"
     */
    public function testPropertyBambino()
    {
    }

    /**
     * Test attribute "progetto"
     */
    public function testPropertyProgetto()
    {
    }

    /**
     * Test attribute "esito"
     */
    public function testPropertyEsito()
    {
    }

    /**
     * Test attribute "id_lascito"
     */
    public function testPropertyIdLascito()
    {
    }

    /**
     * Test attribute "data_attivita"
     */
    public function testPropertyDataAttivita()
    {
    }

    /**
     * Test attribute "ora_attivita"
     */
    public function testPropertyOraAttivita()
    {
    }

    /**
     * Test attribute "utente_assegnatario"
     */
    public function testPropertyUtenteAssegnatario()
    {
    }

    /**
     * Test attribute "gruppo_utenti_assegnatario"
     */
    public function testPropertyGruppoUtentiAssegnatario()
    {
    }

    /**
     * Test attribute "id_gruppo"
     */
    public function testPropertyIdGruppo()
    {
    }

    /**
     * Test attribute "evento"
     */
    public function testPropertyEvento()
    {
    }

    /**
     * Test attribute "sollecito"
     */
    public function testPropertySollecito()
    {
    }

    /**
     * Test attribute "motivo_rifiuto_ask"
     */
    public function testPropertyMotivoRifiutoAsk()
    {
    }

    /**
     * Test attribute "tipo_incidenza"
     */
    public function testPropertyTipoIncidenza()
    {
    }

    /**
     * Test attribute "tipo"
     */
    public function testPropertyTipo()
    {
    }

    /**
     * Test attribute "sottotipo"
     */
    public function testPropertySottotipo()
    {
    }

    /**
     * Test attribute "stato"
     */
    public function testPropertyStato()
    {
    }

    /**
     * Test attribute "importo"
     */
    public function testPropertyImporto()
    {
    }

    /**
     * Test attribute "oggetto"
     */
    public function testPropertyOggetto()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "data_chiusura"
     */
    public function testPropertyDataChiusura()
    {
    }

    /**
     * Test attribute "link"
     */
    public function testPropertyLink()
    {
    }

    /**
     * Test attribute "lotto"
     */
    public function testPropertyLotto()
    {
    }

    /**
     * Test attribute "template"
     */
    public function testPropertyTemplate()
    {
    }
}
