<?php
/**
 * ClientiSubscriptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mentor.ApiRest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ClientiSubscriptionTest Class Doc Comment
 *
 * @category    Class
 * @description ClientiSubscription
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ClientiSubscriptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ClientiSubscription"
     */
    public function testClientiSubscription()
    {
    }

    /**
     * Test attribute "id_cliente"
     */
    public function testPropertyIdCliente()
    {
    }

    /**
     * Test attribute "codice_argomento"
     */
    public function testPropertyCodiceArgomento()
    {
    }

    /**
     * Test attribute "descrizione_argomento"
     */
    public function testPropertyDescrizioneArgomento()
    {
    }

    /**
     * Test attribute "codice_gruppo"
     */
    public function testPropertyCodiceGruppo()
    {
    }

    /**
     * Test attribute "descrizione_gruppo"
     */
    public function testPropertyDescrizioneGruppo()
    {
    }

    /**
     * Test attribute "attiva"
     */
    public function testPropertyAttiva()
    {
    }

    /**
     * Test attribute "data_iscrizione"
     */
    public function testPropertyDataIscrizione()
    {
    }

    /**
     * Test attribute "data_disiscrizione"
     */
    public function testPropertyDataDisiscrizione()
    {
    }
}
