<?php
/**
 * ClientiIndirizziTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mentor.ApiRest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ClientiIndirizziTest Class Doc Comment
 *
 * @category    Class
 * @description ClientiIndirizzi
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ClientiIndirizziTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ClientiIndirizzi"
     */
    public function testClientiIndirizzi()
    {
    }

    /**
     * Test attribute "id_cliente"
     */
    public function testPropertyIdCliente()
    {
    }

    /**
     * Test attribute "tipo_indirizzo"
     */
    public function testPropertyTipoIndirizzo()
    {
    }

    /**
     * Test attribute "descrizione_tipo_indirizzo"
     */
    public function testPropertyDescrizioneTipoIndirizzo()
    {
    }

    /**
     * Test attribute "nome"
     */
    public function testPropertyNome()
    {
    }

    /**
     * Test attribute "dug"
     */
    public function testPropertyDug()
    {
    }

    /**
     * Test attribute "indirizzo"
     */
    public function testPropertyIndirizzo()
    {
    }

    /**
     * Test attribute "civico"
     */
    public function testPropertyCivico()
    {
    }

    /**
     * Test attribute "altro_civico"
     */
    public function testPropertyAltroCivico()
    {
    }

    /**
     * Test attribute "frazione"
     */
    public function testPropertyFrazione()
    {
    }

    /**
     * Test attribute "presso"
     */
    public function testPropertyPresso()
    {
    }

    /**
     * Test attribute "codice_nazione"
     */
    public function testPropertyCodiceNazione()
    {
    }

    /**
     * Test attribute "cap"
     */
    public function testPropertyCap()
    {
    }

    /**
     * Test attribute "localita"
     */
    public function testPropertyLocalita()
    {
    }

    /**
     * Test attribute "provincia"
     */
    public function testPropertyProvincia()
    {
    }

    /**
     * Test attribute "telefono"
     */
    public function testPropertyTelefono()
    {
    }

    /**
     * Test attribute "telefono2"
     */
    public function testPropertyTelefono2()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }
}
