<?php
/**
 * PeriodiciTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mentor.ApiRest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PeriodiciTest Class Doc Comment
 *
 * @category    Class
 * @description Periodici
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PeriodiciTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Periodici"
     */
    public function testPeriodici()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "codice_donatore"
     */
    public function testPropertyCodiceDonatore()
    {
    }

    /**
     * Test attribute "codice_soggetto_versante"
     */
    public function testPropertyCodiceSoggettoVersante()
    {
    }

    /**
     * Test attribute "campagna"
     */
    public function testPropertyCampagna()
    {
    }

    /**
     * Test attribute "centro"
     */
    public function testPropertyCentro()
    {
    }

    /**
     * Test attribute "canale"
     */
    public function testPropertyCanale()
    {
    }

    /**
     * Test attribute "codice_bambino"
     */
    public function testPropertyCodiceBambino()
    {
    }

    /**
     * Test attribute "progetto"
     */
    public function testPropertyProgetto()
    {
    }

    /**
     * Test attribute "tema"
     */
    public function testPropertyTema()
    {
    }

    /**
     * Test attribute "stato"
     */
    public function testPropertyStato()
    {
    }

    /**
     * Test attribute "importo"
     */
    public function testPropertyImporto()
    {
    }

    /**
     * Test attribute "frequenza"
     */
    public function testPropertyFrequenza()
    {
    }

    /**
     * Test attribute "metodo_pagamento"
     */
    public function testPropertyMetodoPagamento()
    {
    }

    /**
     * Test attribute "data_richiesta"
     */
    public function testPropertyDataRichiesta()
    {
    }

    /**
     * Test attribute "ora_richiesta"
     */
    public function testPropertyOraRichiesta()
    {
    }

    /**
     * Test attribute "data_delega"
     */
    public function testPropertyDataDelega()
    {
    }

    /**
     * Test attribute "data_promessa"
     */
    public function testPropertyDataPromessa()
    {
    }

    /**
     * Test attribute "data_prossima_richiesta"
     */
    public function testPropertyDataProssimaRichiesta()
    {
    }

    /**
     * Test attribute "codice_dialogatore_interno"
     */
    public function testPropertyCodiceDialogatoreInterno()
    {
    }

    /**
     * Test attribute "codice_dialogatore_esterno"
     */
    public function testPropertyCodiceDialogatoreEsterno()
    {
    }

    /**
     * Test attribute "nome_dialogatore_esterno"
     */
    public function testPropertyNomeDialogatoreEsterno()
    {
    }

    /**
     * Test attribute "urn"
     */
    public function testPropertyUrn()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "lotto"
     */
    public function testPropertyLotto()
    {
    }

    /**
     * Test attribute "locazione"
     */
    public function testPropertyLocazione()
    {
    }

    /**
     * Test attribute "citta_locazione"
     */
    public function testPropertyCittaLocazione()
    {
    }

    /**
     * Test attribute "nome_titolare"
     */
    public function testPropertyNomeTitolare()
    {
    }

    /**
     * Test attribute "codice_titolare"
     */
    public function testPropertyCodiceTitolare()
    {
    }

    /**
     * Test attribute "iban"
     */
    public function testPropertyIban()
    {
    }

    /**
     * Test attribute "bic"
     */
    public function testPropertyBic()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }

    /**
     * Test attribute "mese_token"
     */
    public function testPropertyMeseToken()
    {
    }

    /**
     * Test attribute "anno_token"
     */
    public function testPropertyAnnoToken()
    {
    }

    /**
     * Test attribute "provider_incasso"
     */
    public function testPropertyProviderIncasso()
    {
    }

    /**
     * Test attribute "carta_prepagata"
     */
    public function testPropertyCartaPrepagata()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "id_capogruppo"
     */
    public function testPropertyIdCapogruppo()
    {
    }

    /**
     * Test attribute "tipo_lead"
     */
    public function testPropertyTipoLead()
    {
    }

    /**
     * Test attribute "genera_sostegno"
     */
    public function testPropertyGeneraSostegno()
    {
    }

    /**
     * Test attribute "preferenza_continente"
     */
    public function testPropertyPreferenzaContinente()
    {
    }

    /**
     * Test attribute "preferenza_nazione"
     */
    public function testPropertyPreferenzaNazione()
    {
    }

    /**
     * Test attribute "preferenza_eta_minima"
     */
    public function testPropertyPreferenzaEtaMinima()
    {
    }

    /**
     * Test attribute "preferenza_eta_massima"
     */
    public function testPropertyPreferenzaEtaMassima()
    {
    }

    /**
     * Test attribute "preferenza_genere"
     */
    public function testPropertyPreferenzaGenere()
    {
    }

    /**
     * Test attribute "id_campagna"
     */
    public function testPropertyIdCampagna()
    {
    }

    /**
     * Test attribute "id_centro"
     */
    public function testPropertyIdCentro()
    {
    }

    /**
     * Test attribute "gruppo_incassi"
     */
    public function testPropertyGruppoIncassi()
    {
    }

    /**
     * Test attribute "codice_nazione"
     */
    public function testPropertyCodiceNazione()
    {
    }

    /**
     * Test attribute "cin_iban"
     */
    public function testPropertyCinIban()
    {
    }

    /**
     * Test attribute "cin_bban"
     */
    public function testPropertyCinBban()
    {
    }

    /**
     * Test attribute "abi"
     */
    public function testPropertyAbi()
    {
    }

    /**
     * Test attribute "cab"
     */
    public function testPropertyCab()
    {
    }

    /**
     * Test attribute "conto"
     */
    public function testPropertyConto()
    {
    }

    /**
     * Test attribute "flag_one_off"
     */
    public function testPropertyFlagOneOff()
    {
    }

    /**
     * Test attribute "masked_pan"
     */
    public function testPropertyMaskedPan()
    {
    }

    /**
     * Test attribute "numero_carta"
     */
    public function testPropertyNumeroCarta()
    {
    }

    /**
     * Test attribute "anno_carta"
     */
    public function testPropertyAnnoCarta()
    {
    }

    /**
     * Test attribute "mese_carta"
     */
    public function testPropertyMeseCarta()
    {
    }

    /**
     * Test attribute "data_inizio_sospensione"
     */
    public function testPropertyDataInizioSospensione()
    {
    }

    /**
     * Test attribute "data_fine_sospensione"
     */
    public function testPropertyDataFineSospensione()
    {
    }

    /**
     * Test attribute "id_motivo_rinuncia"
     */
    public function testPropertyIdMotivoRinuncia()
    {
    }

    /**
     * Test attribute "data_rinuncia"
     */
    public function testPropertyDataRinuncia()
    {
    }
}
