<?php
/**
 * VersamentoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mentor.ApiRest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VersamentoTest Class Doc Comment
 *
 * @category    Class
 * @description Versamento
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VersamentoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Versamento"
     */
    public function testVersamento()
    {
    }

    /**
     * Test attribute "id_versamento"
     */
    public function testPropertyIdVersamento()
    {
    }

    /**
     * Test attribute "id_regolare"
     */
    public function testPropertyIdRegolare()
    {
    }

    /**
     * Test attribute "id_web"
     */
    public function testPropertyIdWeb()
    {
    }

    /**
     * Test attribute "codice_cliente"
     */
    public function testPropertyCodiceCliente()
    {
    }

    /**
     * Test attribute "codice_soggetto_versante"
     */
    public function testPropertyCodiceSoggettoVersante()
    {
    }

    /**
     * Test attribute "codice_partner"
     */
    public function testPropertyCodicePartner()
    {
    }

    /**
     * Test attribute "codice_riferimento"
     */
    public function testPropertyCodiceRiferimento()
    {
    }

    /**
     * Test attribute "campagna"
     */
    public function testPropertyCampagna()
    {
    }

    /**
     * Test attribute "centro"
     */
    public function testPropertyCentro()
    {
    }

    /**
     * Test attribute "canale"
     */
    public function testPropertyCanale()
    {
    }

    /**
     * Test attribute "bambino"
     */
    public function testPropertyBambino()
    {
    }

    /**
     * Test attribute "progetto"
     */
    public function testPropertyProgetto()
    {
    }

    /**
     * Test attribute "conto"
     */
    public function testPropertyConto()
    {
    }

    /**
     * Test attribute "evento"
     */
    public function testPropertyEvento()
    {
    }

    /**
     * Test attribute "codice_transazione"
     */
    public function testPropertyCodiceTransazione()
    {
    }

    /**
     * Test attribute "importo"
     */
    public function testPropertyImporto()
    {
    }

    /**
     * Test attribute "metodo"
     */
    public function testPropertyMetodo()
    {
    }

    /**
     * Test attribute "descrizione_metodo"
     */
    public function testPropertyDescrizioneMetodo()
    {
    }

    /**
     * Test attribute "data_operazione"
     */
    public function testPropertyDataOperazione()
    {
    }

    /**
     * Test attribute "data_valuta"
     */
    public function testPropertyDataValuta()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "tipo"
     */
    public function testPropertyTipo()
    {
    }

    /**
     * Test attribute "sotto_tipo"
     */
    public function testPropertySottoTipo()
    {
    }

    /**
     * Test attribute "lotto"
     */
    public function testPropertyLotto()
    {
    }

    /**
     * Test attribute "escludi_attestato"
     */
    public function testPropertyEscludiAttestato()
    {
    }
}
