<?php
/**
 * Periodici
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mentor.ApiRest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Periodici Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Periodici implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Periodici';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'codice_donatore' => 'string',
        'codice_soggetto_versante' => 'string',
        'campagna' => 'object',
        'centro' => 'object',
        'canale' => 'object',
        'codice_bambino' => 'string',
        'progetto' => 'object',
        'tema' => 'object',
        'stato' => 'object',
        'importo' => 'float',
        'frequenza' => 'int',
        'metodo_pagamento' => 'object',
        'data_richiesta' => 'string',
        'ora_richiesta' => 'string',
        'data_delega' => 'string',
        'data_promessa' => 'string',
        'data_prossima_richiesta' => 'string',
        'codice_dialogatore_interno' => 'string',
        'codice_dialogatore_esterno' => 'string',
        'nome_dialogatore_esterno' => 'string',
        'urn' => 'string',
        'url' => 'string',
        'lotto' => 'string',
        'locazione' => 'string',
        'citta_locazione' => 'string',
        'nome_titolare' => 'string',
        'codice_titolare' => 'string',
        'iban' => 'string',
        'bic' => 'string',
        'token' => 'string',
        'mese_token' => 'string',
        'anno_token' => 'string',
        'provider_incasso' => 'string',
        'carta_prepagata' => 'bool',
        'note' => 'string',
        'id_capogruppo' => 'int',
        'tipo_lead' => 'string',
        'genera_sostegno' => 'bool',
        'preferenza_continente' => 'string',
        'preferenza_nazione' => 'string',
        'preferenza_eta_minima' => 'string',
        'preferenza_eta_massima' => 'string',
        'preferenza_genere' => 'string',
        'id_campagna' => 'int',
        'id_centro' => 'int',
        'gruppo_incassi' => 'int',
        'codice_nazione' => 'string',
        'cin_iban' => 'string',
        'cin_bban' => 'string',
        'abi' => 'string',
        'cab' => 'string',
        'conto' => 'string',
        'flag_one_off' => 'string',
        'masked_pan' => 'string',
        'numero_carta' => 'string',
        'anno_carta' => 'int',
        'mese_carta' => 'int',
        'data_inizio_sospensione' => 'string',
        'data_fine_sospensione' => 'string',
        'id_motivo_rinuncia' => 'int',
        'data_rinuncia' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'int32',
        'codice_donatore' => null,
        'codice_soggetto_versante' => null,
        'campagna' => null,
        'centro' => null,
        'canale' => null,
        'codice_bambino' => null,
        'progetto' => null,
        'tema' => null,
        'stato' => null,
        'importo' => 'float',
        'frequenza' => 'int32',
        'metodo_pagamento' => null,
        'data_richiesta' => null,
        'ora_richiesta' => null,
        'data_delega' => null,
        'data_promessa' => null,
        'data_prossima_richiesta' => null,
        'codice_dialogatore_interno' => null,
        'codice_dialogatore_esterno' => null,
        'nome_dialogatore_esterno' => null,
        'urn' => null,
        'url' => null,
        'lotto' => null,
        'locazione' => null,
        'citta_locazione' => null,
        'nome_titolare' => null,
        'codice_titolare' => null,
        'iban' => null,
        'bic' => null,
        'token' => null,
        'mese_token' => null,
        'anno_token' => null,
        'provider_incasso' => null,
        'carta_prepagata' => null,
        'note' => null,
        'id_capogruppo' => 'int32',
        'tipo_lead' => null,
        'genera_sostegno' => null,
        'preferenza_continente' => null,
        'preferenza_nazione' => null,
        'preferenza_eta_minima' => null,
        'preferenza_eta_massima' => null,
        'preferenza_genere' => null,
        'id_campagna' => 'int32',
        'id_centro' => 'int32',
        'gruppo_incassi' => 'int32',
        'codice_nazione' => null,
        'cin_iban' => null,
        'cin_bban' => null,
        'abi' => null,
        'cab' => null,
        'conto' => null,
        'flag_one_off' => null,
        'masked_pan' => null,
        'numero_carta' => null,
        'anno_carta' => 'int32',
        'mese_carta' => 'int32',
        'data_inizio_sospensione' => null,
        'data_fine_sospensione' => null,
        'id_motivo_rinuncia' => 'int32',
        'data_rinuncia' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'ID',
        'codice_donatore' => 'CodiceDonatore',
        'codice_soggetto_versante' => 'CodiceSoggettoVersante',
        'campagna' => 'Campagna',
        'centro' => 'Centro',
        'canale' => 'Canale',
        'codice_bambino' => 'CodiceBambino',
        'progetto' => 'Progetto',
        'tema' => 'Tema',
        'stato' => 'Stato',
        'importo' => 'Importo',
        'frequenza' => 'Frequenza',
        'metodo_pagamento' => 'MetodoPagamento',
        'data_richiesta' => 'DataRichiesta',
        'ora_richiesta' => 'OraRichiesta',
        'data_delega' => 'DataDelega',
        'data_promessa' => 'DataPromessa',
        'data_prossima_richiesta' => 'DataProssimaRichiesta',
        'codice_dialogatore_interno' => 'CodiceDialogatoreInterno',
        'codice_dialogatore_esterno' => 'CodiceDialogatoreEsterno',
        'nome_dialogatore_esterno' => 'NomeDialogatoreEsterno',
        'urn' => 'urn',
        'url' => 'url',
        'lotto' => 'Lotto',
        'locazione' => 'Locazione',
        'citta_locazione' => 'CittaLocazione',
        'nome_titolare' => 'NomeTitolare',
        'codice_titolare' => 'CodiceTitolare',
        'iban' => 'IBAN',
        'bic' => 'BIC',
        'token' => 'Token',
        'mese_token' => 'MeseToken',
        'anno_token' => 'AnnoToken',
        'provider_incasso' => 'ProviderIncasso',
        'carta_prepagata' => 'CartaPrepagata',
        'note' => 'Note',
        'id_capogruppo' => 'idCapogruppo',
        'tipo_lead' => 'TipoLead',
        'genera_sostegno' => 'GeneraSostegno',
        'preferenza_continente' => 'PreferenzaContinente',
        'preferenza_nazione' => 'PreferenzaNazione',
        'preferenza_eta_minima' => 'PreferenzaEtaMinima',
        'preferenza_eta_massima' => 'PreferenzaEtaMassima',
        'preferenza_genere' => 'PreferenzaGenere',
        'id_campagna' => 'idCampagna',
        'id_centro' => 'idCentro',
        'gruppo_incassi' => 'GruppoIncassi',
        'codice_nazione' => 'CodiceNazione',
        'cin_iban' => 'cinIban',
        'cin_bban' => 'cinBban',
        'abi' => 'ABI',
        'cab' => 'CAB',
        'conto' => 'Conto',
        'flag_one_off' => 'FlagOneOff',
        'masked_pan' => 'MaskedPan',
        'numero_carta' => 'NumeroCarta',
        'anno_carta' => 'AnnoCarta',
        'mese_carta' => 'MeseCarta',
        'data_inizio_sospensione' => 'DataInizioSospensione',
        'data_fine_sospensione' => 'DataFineSospensione',
        'id_motivo_rinuncia' => 'idMotivoRinuncia',
        'data_rinuncia' => 'DataRinuncia'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'codice_donatore' => 'setCodiceDonatore',
        'codice_soggetto_versante' => 'setCodiceSoggettoVersante',
        'campagna' => 'setCampagna',
        'centro' => 'setCentro',
        'canale' => 'setCanale',
        'codice_bambino' => 'setCodiceBambino',
        'progetto' => 'setProgetto',
        'tema' => 'setTema',
        'stato' => 'setStato',
        'importo' => 'setImporto',
        'frequenza' => 'setFrequenza',
        'metodo_pagamento' => 'setMetodoPagamento',
        'data_richiesta' => 'setDataRichiesta',
        'ora_richiesta' => 'setOraRichiesta',
        'data_delega' => 'setDataDelega',
        'data_promessa' => 'setDataPromessa',
        'data_prossima_richiesta' => 'setDataProssimaRichiesta',
        'codice_dialogatore_interno' => 'setCodiceDialogatoreInterno',
        'codice_dialogatore_esterno' => 'setCodiceDialogatoreEsterno',
        'nome_dialogatore_esterno' => 'setNomeDialogatoreEsterno',
        'urn' => 'setUrn',
        'url' => 'setUrl',
        'lotto' => 'setLotto',
        'locazione' => 'setLocazione',
        'citta_locazione' => 'setCittaLocazione',
        'nome_titolare' => 'setNomeTitolare',
        'codice_titolare' => 'setCodiceTitolare',
        'iban' => 'setIban',
        'bic' => 'setBic',
        'token' => 'setToken',
        'mese_token' => 'setMeseToken',
        'anno_token' => 'setAnnoToken',
        'provider_incasso' => 'setProviderIncasso',
        'carta_prepagata' => 'setCartaPrepagata',
        'note' => 'setNote',
        'id_capogruppo' => 'setIdCapogruppo',
        'tipo_lead' => 'setTipoLead',
        'genera_sostegno' => 'setGeneraSostegno',
        'preferenza_continente' => 'setPreferenzaContinente',
        'preferenza_nazione' => 'setPreferenzaNazione',
        'preferenza_eta_minima' => 'setPreferenzaEtaMinima',
        'preferenza_eta_massima' => 'setPreferenzaEtaMassima',
        'preferenza_genere' => 'setPreferenzaGenere',
        'id_campagna' => 'setIdCampagna',
        'id_centro' => 'setIdCentro',
        'gruppo_incassi' => 'setGruppoIncassi',
        'codice_nazione' => 'setCodiceNazione',
        'cin_iban' => 'setCinIban',
        'cin_bban' => 'setCinBban',
        'abi' => 'setAbi',
        'cab' => 'setCab',
        'conto' => 'setConto',
        'flag_one_off' => 'setFlagOneOff',
        'masked_pan' => 'setMaskedPan',
        'numero_carta' => 'setNumeroCarta',
        'anno_carta' => 'setAnnoCarta',
        'mese_carta' => 'setMeseCarta',
        'data_inizio_sospensione' => 'setDataInizioSospensione',
        'data_fine_sospensione' => 'setDataFineSospensione',
        'id_motivo_rinuncia' => 'setIdMotivoRinuncia',
        'data_rinuncia' => 'setDataRinuncia'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'codice_donatore' => 'getCodiceDonatore',
        'codice_soggetto_versante' => 'getCodiceSoggettoVersante',
        'campagna' => 'getCampagna',
        'centro' => 'getCentro',
        'canale' => 'getCanale',
        'codice_bambino' => 'getCodiceBambino',
        'progetto' => 'getProgetto',
        'tema' => 'getTema',
        'stato' => 'getStato',
        'importo' => 'getImporto',
        'frequenza' => 'getFrequenza',
        'metodo_pagamento' => 'getMetodoPagamento',
        'data_richiesta' => 'getDataRichiesta',
        'ora_richiesta' => 'getOraRichiesta',
        'data_delega' => 'getDataDelega',
        'data_promessa' => 'getDataPromessa',
        'data_prossima_richiesta' => 'getDataProssimaRichiesta',
        'codice_dialogatore_interno' => 'getCodiceDialogatoreInterno',
        'codice_dialogatore_esterno' => 'getCodiceDialogatoreEsterno',
        'nome_dialogatore_esterno' => 'getNomeDialogatoreEsterno',
        'urn' => 'getUrn',
        'url' => 'getUrl',
        'lotto' => 'getLotto',
        'locazione' => 'getLocazione',
        'citta_locazione' => 'getCittaLocazione',
        'nome_titolare' => 'getNomeTitolare',
        'codice_titolare' => 'getCodiceTitolare',
        'iban' => 'getIban',
        'bic' => 'getBic',
        'token' => 'getToken',
        'mese_token' => 'getMeseToken',
        'anno_token' => 'getAnnoToken',
        'provider_incasso' => 'getProviderIncasso',
        'carta_prepagata' => 'getCartaPrepagata',
        'note' => 'getNote',
        'id_capogruppo' => 'getIdCapogruppo',
        'tipo_lead' => 'getTipoLead',
        'genera_sostegno' => 'getGeneraSostegno',
        'preferenza_continente' => 'getPreferenzaContinente',
        'preferenza_nazione' => 'getPreferenzaNazione',
        'preferenza_eta_minima' => 'getPreferenzaEtaMinima',
        'preferenza_eta_massima' => 'getPreferenzaEtaMassima',
        'preferenza_genere' => 'getPreferenzaGenere',
        'id_campagna' => 'getIdCampagna',
        'id_centro' => 'getIdCentro',
        'gruppo_incassi' => 'getGruppoIncassi',
        'codice_nazione' => 'getCodiceNazione',
        'cin_iban' => 'getCinIban',
        'cin_bban' => 'getCinBban',
        'abi' => 'getAbi',
        'cab' => 'getCab',
        'conto' => 'getConto',
        'flag_one_off' => 'getFlagOneOff',
        'masked_pan' => 'getMaskedPan',
        'numero_carta' => 'getNumeroCarta',
        'anno_carta' => 'getAnnoCarta',
        'mese_carta' => 'getMeseCarta',
        'data_inizio_sospensione' => 'getDataInizioSospensione',
        'data_fine_sospensione' => 'getDataFineSospensione',
        'id_motivo_rinuncia' => 'getIdMotivoRinuncia',
        'data_rinuncia' => 'getDataRinuncia'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['codice_donatore'] = isset($data['codice_donatore']) ? $data['codice_donatore'] : null;
        $this->container['codice_soggetto_versante'] = isset($data['codice_soggetto_versante']) ? $data['codice_soggetto_versante'] : null;
        $this->container['campagna'] = isset($data['campagna']) ? $data['campagna'] : null;
        $this->container['centro'] = isset($data['centro']) ? $data['centro'] : null;
        $this->container['canale'] = isset($data['canale']) ? $data['canale'] : null;
        $this->container['codice_bambino'] = isset($data['codice_bambino']) ? $data['codice_bambino'] : null;
        $this->container['progetto'] = isset($data['progetto']) ? $data['progetto'] : null;
        $this->container['tema'] = isset($data['tema']) ? $data['tema'] : null;
        $this->container['stato'] = isset($data['stato']) ? $data['stato'] : null;
        $this->container['importo'] = isset($data['importo']) ? $data['importo'] : null;
        $this->container['frequenza'] = isset($data['frequenza']) ? $data['frequenza'] : null;
        $this->container['metodo_pagamento'] = isset($data['metodo_pagamento']) ? $data['metodo_pagamento'] : null;
        $this->container['data_richiesta'] = isset($data['data_richiesta']) ? $data['data_richiesta'] : null;
        $this->container['ora_richiesta'] = isset($data['ora_richiesta']) ? $data['ora_richiesta'] : null;
        $this->container['data_delega'] = isset($data['data_delega']) ? $data['data_delega'] : null;
        $this->container['data_promessa'] = isset($data['data_promessa']) ? $data['data_promessa'] : null;
        $this->container['data_prossima_richiesta'] = isset($data['data_prossima_richiesta']) ? $data['data_prossima_richiesta'] : null;
        $this->container['codice_dialogatore_interno'] = isset($data['codice_dialogatore_interno']) ? $data['codice_dialogatore_interno'] : null;
        $this->container['codice_dialogatore_esterno'] = isset($data['codice_dialogatore_esterno']) ? $data['codice_dialogatore_esterno'] : null;
        $this->container['nome_dialogatore_esterno'] = isset($data['nome_dialogatore_esterno']) ? $data['nome_dialogatore_esterno'] : null;
        $this->container['urn'] = isset($data['urn']) ? $data['urn'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['lotto'] = isset($data['lotto']) ? $data['lotto'] : null;
        $this->container['locazione'] = isset($data['locazione']) ? $data['locazione'] : null;
        $this->container['citta_locazione'] = isset($data['citta_locazione']) ? $data['citta_locazione'] : null;
        $this->container['nome_titolare'] = isset($data['nome_titolare']) ? $data['nome_titolare'] : null;
        $this->container['codice_titolare'] = isset($data['codice_titolare']) ? $data['codice_titolare'] : null;
        $this->container['iban'] = isset($data['iban']) ? $data['iban'] : null;
        $this->container['bic'] = isset($data['bic']) ? $data['bic'] : null;
        $this->container['token'] = isset($data['token']) ? $data['token'] : null;
        $this->container['mese_token'] = isset($data['mese_token']) ? $data['mese_token'] : null;
        $this->container['anno_token'] = isset($data['anno_token']) ? $data['anno_token'] : null;
        $this->container['provider_incasso'] = isset($data['provider_incasso']) ? $data['provider_incasso'] : null;
        $this->container['carta_prepagata'] = isset($data['carta_prepagata']) ? $data['carta_prepagata'] : null;
        $this->container['note'] = isset($data['note']) ? $data['note'] : null;
        $this->container['id_capogruppo'] = isset($data['id_capogruppo']) ? $data['id_capogruppo'] : null;
        $this->container['tipo_lead'] = isset($data['tipo_lead']) ? $data['tipo_lead'] : null;
        $this->container['genera_sostegno'] = isset($data['genera_sostegno']) ? $data['genera_sostegno'] : null;
        $this->container['preferenza_continente'] = isset($data['preferenza_continente']) ? $data['preferenza_continente'] : null;
        $this->container['preferenza_nazione'] = isset($data['preferenza_nazione']) ? $data['preferenza_nazione'] : null;
        $this->container['preferenza_eta_minima'] = isset($data['preferenza_eta_minima']) ? $data['preferenza_eta_minima'] : null;
        $this->container['preferenza_eta_massima'] = isset($data['preferenza_eta_massima']) ? $data['preferenza_eta_massima'] : null;
        $this->container['preferenza_genere'] = isset($data['preferenza_genere']) ? $data['preferenza_genere'] : null;
        $this->container['id_campagna'] = isset($data['id_campagna']) ? $data['id_campagna'] : null;
        $this->container['id_centro'] = isset($data['id_centro']) ? $data['id_centro'] : null;
        $this->container['gruppo_incassi'] = isset($data['gruppo_incassi']) ? $data['gruppo_incassi'] : null;
        $this->container['codice_nazione'] = isset($data['codice_nazione']) ? $data['codice_nazione'] : null;
        $this->container['cin_iban'] = isset($data['cin_iban']) ? $data['cin_iban'] : null;
        $this->container['cin_bban'] = isset($data['cin_bban']) ? $data['cin_bban'] : null;
        $this->container['abi'] = isset($data['abi']) ? $data['abi'] : null;
        $this->container['cab'] = isset($data['cab']) ? $data['cab'] : null;
        $this->container['conto'] = isset($data['conto']) ? $data['conto'] : null;
        $this->container['flag_one_off'] = isset($data['flag_one_off']) ? $data['flag_one_off'] : null;
        $this->container['masked_pan'] = isset($data['masked_pan']) ? $data['masked_pan'] : null;
        $this->container['numero_carta'] = isset($data['numero_carta']) ? $data['numero_carta'] : null;
        $this->container['anno_carta'] = isset($data['anno_carta']) ? $data['anno_carta'] : null;
        $this->container['mese_carta'] = isset($data['mese_carta']) ? $data['mese_carta'] : null;
        $this->container['data_inizio_sospensione'] = isset($data['data_inizio_sospensione']) ? $data['data_inizio_sospensione'] : null;
        $this->container['data_fine_sospensione'] = isset($data['data_fine_sospensione']) ? $data['data_fine_sospensione'] : null;
        $this->container['id_motivo_rinuncia'] = isset($data['id_motivo_rinuncia']) ? $data['id_motivo_rinuncia'] : null;
        $this->container['data_rinuncia'] = isset($data['data_rinuncia']) ? $data['data_rinuncia'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets codice_donatore
     *
     * @return string
     */
    public function getCodiceDonatore()
    {
        return $this->container['codice_donatore'];
    }

    /**
     * Sets codice_donatore
     *
     * @param string $codice_donatore codice_donatore
     *
     * @return $this
     */
    public function setCodiceDonatore($codice_donatore)
    {
        $this->container['codice_donatore'] = $codice_donatore;

        return $this;
    }

    /**
     * Gets codice_soggetto_versante
     *
     * @return string
     */
    public function getCodiceSoggettoVersante()
    {
        return $this->container['codice_soggetto_versante'];
    }

    /**
     * Sets codice_soggetto_versante
     *
     * @param string $codice_soggetto_versante codice_soggetto_versante
     *
     * @return $this
     */
    public function setCodiceSoggettoVersante($codice_soggetto_versante)
    {
        $this->container['codice_soggetto_versante'] = $codice_soggetto_versante;

        return $this;
    }

    /**
     * Gets campagna
     *
     * @return object
     */
    public function getCampagna()
    {
        return $this->container['campagna'];
    }

    /**
     * Sets campagna
     *
     * @param object $campagna campagna
     *
     * @return $this
     */
    public function setCampagna($campagna)
    {
        $this->container['campagna'] = $campagna;

        return $this;
    }

    /**
     * Gets centro
     *
     * @return object
     */
    public function getCentro()
    {
        return $this->container['centro'];
    }

    /**
     * Sets centro
     *
     * @param object $centro centro
     *
     * @return $this
     */
    public function setCentro($centro)
    {
        $this->container['centro'] = $centro;

        return $this;
    }

    /**
     * Gets canale
     *
     * @return object
     */
    public function getCanale()
    {
        return $this->container['canale'];
    }

    /**
     * Sets canale
     *
     * @param object $canale canale
     *
     * @return $this
     */
    public function setCanale($canale)
    {
        $this->container['canale'] = $canale;

        return $this;
    }

    /**
     * Gets codice_bambino
     *
     * @return string
     */
    public function getCodiceBambino()
    {
        return $this->container['codice_bambino'];
    }

    /**
     * Sets codice_bambino
     *
     * @param string $codice_bambino codice_bambino
     *
     * @return $this
     */
    public function setCodiceBambino($codice_bambino)
    {
        $this->container['codice_bambino'] = $codice_bambino;

        return $this;
    }

    /**
     * Gets progetto
     *
     * @return object
     */
    public function getProgetto()
    {
        return $this->container['progetto'];
    }

    /**
     * Sets progetto
     *
     * @param object $progetto progetto
     *
     * @return $this
     */
    public function setProgetto($progetto)
    {
        $this->container['progetto'] = $progetto;

        return $this;
    }

    /**
     * Gets tema
     *
     * @return object
     */
    public function getTema()
    {
        return $this->container['tema'];
    }

    /**
     * Sets tema
     *
     * @param object $tema tema
     *
     * @return $this
     */
    public function setTema($tema)
    {
        $this->container['tema'] = $tema;

        return $this;
    }

    /**
     * Gets stato
     *
     * @return object
     */
    public function getStato()
    {
        return $this->container['stato'];
    }

    /**
     * Sets stato
     *
     * @param object $stato stato
     *
     * @return $this
     */
    public function setStato($stato)
    {
        $this->container['stato'] = $stato;

        return $this;
    }

    /**
     * Gets importo
     *
     * @return float
     */
    public function getImporto()
    {
        return $this->container['importo'];
    }

    /**
     * Sets importo
     *
     * @param float $importo importo
     *
     * @return $this
     */
    public function setImporto($importo)
    {
        $this->container['importo'] = $importo;

        return $this;
    }

    /**
     * Gets frequenza
     *
     * @return int
     */
    public function getFrequenza()
    {
        return $this->container['frequenza'];
    }

    /**
     * Sets frequenza
     *
     * @param int $frequenza frequenza
     *
     * @return $this
     */
    public function setFrequenza($frequenza)
    {
        $this->container['frequenza'] = $frequenza;

        return $this;
    }

    /**
     * Gets metodo_pagamento
     *
     * @return object
     */
    public function getMetodoPagamento()
    {
        return $this->container['metodo_pagamento'];
    }

    /**
     * Sets metodo_pagamento
     *
     * @param object $metodo_pagamento metodo_pagamento
     *
     * @return $this
     */
    public function setMetodoPagamento($metodo_pagamento)
    {
        $this->container['metodo_pagamento'] = $metodo_pagamento;

        return $this;
    }

    /**
     * Gets data_richiesta
     *
     * @return string
     */
    public function getDataRichiesta()
    {
        return $this->container['data_richiesta'];
    }

    /**
     * Sets data_richiesta
     *
     * @param string $data_richiesta data_richiesta
     *
     * @return $this
     */
    public function setDataRichiesta($data_richiesta)
    {
        $this->container['data_richiesta'] = $data_richiesta;

        return $this;
    }

    /**
     * Gets ora_richiesta
     *
     * @return string
     */
    public function getOraRichiesta()
    {
        return $this->container['ora_richiesta'];
    }

    /**
     * Sets ora_richiesta
     *
     * @param string $ora_richiesta ora_richiesta
     *
     * @return $this
     */
    public function setOraRichiesta($ora_richiesta)
    {
        $this->container['ora_richiesta'] = $ora_richiesta;

        return $this;
    }

    /**
     * Gets data_delega
     *
     * @return string
     */
    public function getDataDelega()
    {
        return $this->container['data_delega'];
    }

    /**
     * Sets data_delega
     *
     * @param string $data_delega data_delega
     *
     * @return $this
     */
    public function setDataDelega($data_delega)
    {
        $this->container['data_delega'] = $data_delega;

        return $this;
    }

    /**
     * Gets data_promessa
     *
     * @return string
     */
    public function getDataPromessa()
    {
        return $this->container['data_promessa'];
    }

    /**
     * Sets data_promessa
     *
     * @param string $data_promessa data_promessa
     *
     * @return $this
     */
    public function setDataPromessa($data_promessa)
    {
        $this->container['data_promessa'] = $data_promessa;

        return $this;
    }

    /**
     * Gets data_prossima_richiesta
     *
     * @return string
     */
    public function getDataProssimaRichiesta()
    {
        return $this->container['data_prossima_richiesta'];
    }

    /**
     * Sets data_prossima_richiesta
     *
     * @param string $data_prossima_richiesta data_prossima_richiesta
     *
     * @return $this
     */
    public function setDataProssimaRichiesta($data_prossima_richiesta)
    {
        $this->container['data_prossima_richiesta'] = $data_prossima_richiesta;

        return $this;
    }

    /**
     * Gets codice_dialogatore_interno
     *
     * @return string
     */
    public function getCodiceDialogatoreInterno()
    {
        return $this->container['codice_dialogatore_interno'];
    }

    /**
     * Sets codice_dialogatore_interno
     *
     * @param string $codice_dialogatore_interno codice_dialogatore_interno
     *
     * @return $this
     */
    public function setCodiceDialogatoreInterno($codice_dialogatore_interno)
    {
        $this->container['codice_dialogatore_interno'] = $codice_dialogatore_interno;

        return $this;
    }

    /**
     * Gets codice_dialogatore_esterno
     *
     * @return string
     */
    public function getCodiceDialogatoreEsterno()
    {
        return $this->container['codice_dialogatore_esterno'];
    }

    /**
     * Sets codice_dialogatore_esterno
     *
     * @param string $codice_dialogatore_esterno codice_dialogatore_esterno
     *
     * @return $this
     */
    public function setCodiceDialogatoreEsterno($codice_dialogatore_esterno)
    {
        $this->container['codice_dialogatore_esterno'] = $codice_dialogatore_esterno;

        return $this;
    }

    /**
     * Gets nome_dialogatore_esterno
     *
     * @return string
     */
    public function getNomeDialogatoreEsterno()
    {
        return $this->container['nome_dialogatore_esterno'];
    }

    /**
     * Sets nome_dialogatore_esterno
     *
     * @param string $nome_dialogatore_esterno nome_dialogatore_esterno
     *
     * @return $this
     */
    public function setNomeDialogatoreEsterno($nome_dialogatore_esterno)
    {
        $this->container['nome_dialogatore_esterno'] = $nome_dialogatore_esterno;

        return $this;
    }

    /**
     * Gets urn
     *
     * @return string
     */
    public function getUrn()
    {
        return $this->container['urn'];
    }

    /**
     * Sets urn
     *
     * @param string $urn urn
     *
     * @return $this
     */
    public function setUrn($urn)
    {
        $this->container['urn'] = $urn;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets lotto
     *
     * @return string
     */
    public function getLotto()
    {
        return $this->container['lotto'];
    }

    /**
     * Sets lotto
     *
     * @param string $lotto lotto
     *
     * @return $this
     */
    public function setLotto($lotto)
    {
        $this->container['lotto'] = $lotto;

        return $this;
    }

    /**
     * Gets locazione
     *
     * @return string
     */
    public function getLocazione()
    {
        return $this->container['locazione'];
    }

    /**
     * Sets locazione
     *
     * @param string $locazione locazione
     *
     * @return $this
     */
    public function setLocazione($locazione)
    {
        $this->container['locazione'] = $locazione;

        return $this;
    }

    /**
     * Gets citta_locazione
     *
     * @return string
     */
    public function getCittaLocazione()
    {
        return $this->container['citta_locazione'];
    }

    /**
     * Sets citta_locazione
     *
     * @param string $citta_locazione citta_locazione
     *
     * @return $this
     */
    public function setCittaLocazione($citta_locazione)
    {
        $this->container['citta_locazione'] = $citta_locazione;

        return $this;
    }

    /**
     * Gets nome_titolare
     *
     * @return string
     */
    public function getNomeTitolare()
    {
        return $this->container['nome_titolare'];
    }

    /**
     * Sets nome_titolare
     *
     * @param string $nome_titolare nome_titolare
     *
     * @return $this
     */
    public function setNomeTitolare($nome_titolare)
    {
        $this->container['nome_titolare'] = $nome_titolare;

        return $this;
    }

    /**
     * Gets codice_titolare
     *
     * @return string
     */
    public function getCodiceTitolare()
    {
        return $this->container['codice_titolare'];
    }

    /**
     * Sets codice_titolare
     *
     * @param string $codice_titolare codice_titolare
     *
     * @return $this
     */
    public function setCodiceTitolare($codice_titolare)
    {
        $this->container['codice_titolare'] = $codice_titolare;

        return $this;
    }

    /**
     * Gets iban
     *
     * @return string
     */
    public function getIban()
    {
        return $this->container['iban'];
    }

    /**
     * Sets iban
     *
     * @param string $iban iban
     *
     * @return $this
     */
    public function setIban($iban)
    {
        $this->container['iban'] = $iban;

        return $this;
    }

    /**
     * Gets bic
     *
     * @return string
     */
    public function getBic()
    {
        return $this->container['bic'];
    }

    /**
     * Sets bic
     *
     * @param string $bic bic
     *
     * @return $this
     */
    public function setBic($bic)
    {
        $this->container['bic'] = $bic;

        return $this;
    }

    /**
     * Gets token
     *
     * @return string
     */
    public function getToken()
    {
        return $this->container['token'];
    }

    /**
     * Sets token
     *
     * @param string $token token
     *
     * @return $this
     */
    public function setToken($token)
    {
        $this->container['token'] = $token;

        return $this;
    }

    /**
     * Gets mese_token
     *
     * @return string
     */
    public function getMeseToken()
    {
        return $this->container['mese_token'];
    }

    /**
     * Sets mese_token
     *
     * @param string $mese_token mese_token
     *
     * @return $this
     */
    public function setMeseToken($mese_token)
    {
        $this->container['mese_token'] = $mese_token;

        return $this;
    }

    /**
     * Gets anno_token
     *
     * @return string
     */
    public function getAnnoToken()
    {
        return $this->container['anno_token'];
    }

    /**
     * Sets anno_token
     *
     * @param string $anno_token anno_token
     *
     * @return $this
     */
    public function setAnnoToken($anno_token)
    {
        $this->container['anno_token'] = $anno_token;

        return $this;
    }

    /**
     * Gets provider_incasso
     *
     * @return string
     */
    public function getProviderIncasso()
    {
        return $this->container['provider_incasso'];
    }

    /**
     * Sets provider_incasso
     *
     * @param string $provider_incasso provider_incasso
     *
     * @return $this
     */
    public function setProviderIncasso($provider_incasso)
    {
        $this->container['provider_incasso'] = $provider_incasso;

        return $this;
    }

    /**
     * Gets carta_prepagata
     *
     * @return bool
     */
    public function getCartaPrepagata()
    {
        return $this->container['carta_prepagata'];
    }

    /**
     * Sets carta_prepagata
     *
     * @param bool $carta_prepagata carta_prepagata
     *
     * @return $this
     */
    public function setCartaPrepagata($carta_prepagata)
    {
        $this->container['carta_prepagata'] = $carta_prepagata;

        return $this;
    }

    /**
     * Gets note
     *
     * @return string
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param string $note note
     *
     * @return $this
     */
    public function setNote($note)
    {
        $this->container['note'] = $note;

        return $this;
    }

    /**
     * Gets id_capogruppo
     *
     * @return int
     */
    public function getIdCapogruppo()
    {
        return $this->container['id_capogruppo'];
    }

    /**
     * Sets id_capogruppo
     *
     * @param int $id_capogruppo id_capogruppo
     *
     * @return $this
     */
    public function setIdCapogruppo($id_capogruppo)
    {
        $this->container['id_capogruppo'] = $id_capogruppo;

        return $this;
    }

    /**
     * Gets tipo_lead
     *
     * @return string
     */
    public function getTipoLead()
    {
        return $this->container['tipo_lead'];
    }

    /**
     * Sets tipo_lead
     *
     * @param string $tipo_lead tipo_lead
     *
     * @return $this
     */
    public function setTipoLead($tipo_lead)
    {
        $this->container['tipo_lead'] = $tipo_lead;

        return $this;
    }

    /**
     * Gets genera_sostegno
     *
     * @return bool
     */
    public function getGeneraSostegno()
    {
        return $this->container['genera_sostegno'];
    }

    /**
     * Sets genera_sostegno
     *
     * @param bool $genera_sostegno genera_sostegno
     *
     * @return $this
     */
    public function setGeneraSostegno($genera_sostegno)
    {
        $this->container['genera_sostegno'] = $genera_sostegno;

        return $this;
    }

    /**
     * Gets preferenza_continente
     *
     * @return string
     */
    public function getPreferenzaContinente()
    {
        return $this->container['preferenza_continente'];
    }

    /**
     * Sets preferenza_continente
     *
     * @param string $preferenza_continente preferenza_continente
     *
     * @return $this
     */
    public function setPreferenzaContinente($preferenza_continente)
    {
        $this->container['preferenza_continente'] = $preferenza_continente;

        return $this;
    }

    /**
     * Gets preferenza_nazione
     *
     * @return string
     */
    public function getPreferenzaNazione()
    {
        return $this->container['preferenza_nazione'];
    }

    /**
     * Sets preferenza_nazione
     *
     * @param string $preferenza_nazione preferenza_nazione
     *
     * @return $this
     */
    public function setPreferenzaNazione($preferenza_nazione)
    {
        $this->container['preferenza_nazione'] = $preferenza_nazione;

        return $this;
    }

    /**
     * Gets preferenza_eta_minima
     *
     * @return string
     */
    public function getPreferenzaEtaMinima()
    {
        return $this->container['preferenza_eta_minima'];
    }

    /**
     * Sets preferenza_eta_minima
     *
     * @param string $preferenza_eta_minima preferenza_eta_minima
     *
     * @return $this
     */
    public function setPreferenzaEtaMinima($preferenza_eta_minima)
    {
        $this->container['preferenza_eta_minima'] = $preferenza_eta_minima;

        return $this;
    }

    /**
     * Gets preferenza_eta_massima
     *
     * @return string
     */
    public function getPreferenzaEtaMassima()
    {
        return $this->container['preferenza_eta_massima'];
    }

    /**
     * Sets preferenza_eta_massima
     *
     * @param string $preferenza_eta_massima preferenza_eta_massima
     *
     * @return $this
     */
    public function setPreferenzaEtaMassima($preferenza_eta_massima)
    {
        $this->container['preferenza_eta_massima'] = $preferenza_eta_massima;

        return $this;
    }

    /**
     * Gets preferenza_genere
     *
     * @return string
     */
    public function getPreferenzaGenere()
    {
        return $this->container['preferenza_genere'];
    }

    /**
     * Sets preferenza_genere
     *
     * @param string $preferenza_genere preferenza_genere
     *
     * @return $this
     */
    public function setPreferenzaGenere($preferenza_genere)
    {
        $this->container['preferenza_genere'] = $preferenza_genere;

        return $this;
    }

    /**
     * Gets id_campagna
     *
     * @return int
     */
    public function getIdCampagna()
    {
        return $this->container['id_campagna'];
    }

    /**
     * Sets id_campagna
     *
     * @param int $id_campagna id_campagna
     *
     * @return $this
     */
    public function setIdCampagna($id_campagna)
    {
        $this->container['id_campagna'] = $id_campagna;

        return $this;
    }

    /**
     * Gets id_centro
     *
     * @return int
     */
    public function getIdCentro()
    {
        return $this->container['id_centro'];
    }

    /**
     * Sets id_centro
     *
     * @param int $id_centro id_centro
     *
     * @return $this
     */
    public function setIdCentro($id_centro)
    {
        $this->container['id_centro'] = $id_centro;

        return $this;
    }

    /**
     * Gets gruppo_incassi
     *
     * @return int
     */
    public function getGruppoIncassi()
    {
        return $this->container['gruppo_incassi'];
    }

    /**
     * Sets gruppo_incassi
     *
     * @param int $gruppo_incassi gruppo_incassi
     *
     * @return $this
     */
    public function setGruppoIncassi($gruppo_incassi)
    {
        $this->container['gruppo_incassi'] = $gruppo_incassi;

        return $this;
    }

    /**
     * Gets codice_nazione
     *
     * @return string
     */
    public function getCodiceNazione()
    {
        return $this->container['codice_nazione'];
    }

    /**
     * Sets codice_nazione
     *
     * @param string $codice_nazione codice_nazione
     *
     * @return $this
     */
    public function setCodiceNazione($codice_nazione)
    {
        $this->container['codice_nazione'] = $codice_nazione;

        return $this;
    }

    /**
     * Gets cin_iban
     *
     * @return string
     */
    public function getCinIban()
    {
        return $this->container['cin_iban'];
    }

    /**
     * Sets cin_iban
     *
     * @param string $cin_iban cin_iban
     *
     * @return $this
     */
    public function setCinIban($cin_iban)
    {
        $this->container['cin_iban'] = $cin_iban;

        return $this;
    }

    /**
     * Gets cin_bban
     *
     * @return string
     */
    public function getCinBban()
    {
        return $this->container['cin_bban'];
    }

    /**
     * Sets cin_bban
     *
     * @param string $cin_bban cin_bban
     *
     * @return $this
     */
    public function setCinBban($cin_bban)
    {
        $this->container['cin_bban'] = $cin_bban;

        return $this;
    }

    /**
     * Gets abi
     *
     * @return string
     */
    public function getAbi()
    {
        return $this->container['abi'];
    }

    /**
     * Sets abi
     *
     * @param string $abi abi
     *
     * @return $this
     */
    public function setAbi($abi)
    {
        $this->container['abi'] = $abi;

        return $this;
    }

    /**
     * Gets cab
     *
     * @return string
     */
    public function getCab()
    {
        return $this->container['cab'];
    }

    /**
     * Sets cab
     *
     * @param string $cab cab
     *
     * @return $this
     */
    public function setCab($cab)
    {
        $this->container['cab'] = $cab;

        return $this;
    }

    /**
     * Gets conto
     *
     * @return string
     */
    public function getConto()
    {
        return $this->container['conto'];
    }

    /**
     * Sets conto
     *
     * @param string $conto conto
     *
     * @return $this
     */
    public function setConto($conto)
    {
        $this->container['conto'] = $conto;

        return $this;
    }

    /**
     * Gets flag_one_off
     *
     * @return string
     */
    public function getFlagOneOff()
    {
        return $this->container['flag_one_off'];
    }

    /**
     * Sets flag_one_off
     *
     * @param string $flag_one_off flag_one_off
     *
     * @return $this
     */
    public function setFlagOneOff($flag_one_off)
    {
        $this->container['flag_one_off'] = $flag_one_off;

        return $this;
    }

    /**
     * Gets masked_pan
     *
     * @return string
     */
    public function getMaskedPan()
    {
        return $this->container['masked_pan'];
    }

    /**
     * Sets masked_pan
     *
     * @param string $masked_pan masked_pan
     *
     * @return $this
     */
    public function setMaskedPan($masked_pan)
    {
        $this->container['masked_pan'] = $masked_pan;

        return $this;
    }

    /**
     * Gets numero_carta
     *
     * @return string
     */
    public function getNumeroCarta()
    {
        return $this->container['numero_carta'];
    }

    /**
     * Sets numero_carta
     *
     * @param string $numero_carta numero_carta
     *
     * @return $this
     */
    public function setNumeroCarta($numero_carta)
    {
        $this->container['numero_carta'] = $numero_carta;

        return $this;
    }

    /**
     * Gets anno_carta
     *
     * @return int
     */
    public function getAnnoCarta()
    {
        return $this->container['anno_carta'];
    }

    /**
     * Sets anno_carta
     *
     * @param int $anno_carta anno_carta
     *
     * @return $this
     */
    public function setAnnoCarta($anno_carta)
    {
        $this->container['anno_carta'] = $anno_carta;

        return $this;
    }

    /**
     * Gets mese_carta
     *
     * @return int
     */
    public function getMeseCarta()
    {
        return $this->container['mese_carta'];
    }

    /**
     * Sets mese_carta
     *
     * @param int $mese_carta mese_carta
     *
     * @return $this
     */
    public function setMeseCarta($mese_carta)
    {
        $this->container['mese_carta'] = $mese_carta;

        return $this;
    }

    /**
     * Gets data_inizio_sospensione
     *
     * @return string
     */
    public function getDataInizioSospensione()
    {
        return $this->container['data_inizio_sospensione'];
    }

    /**
     * Sets data_inizio_sospensione
     *
     * @param string $data_inizio_sospensione data_inizio_sospensione
     *
     * @return $this
     */
    public function setDataInizioSospensione($data_inizio_sospensione)
    {
        $this->container['data_inizio_sospensione'] = $data_inizio_sospensione;

        return $this;
    }

    /**
     * Gets data_fine_sospensione
     *
     * @return string
     */
    public function getDataFineSospensione()
    {
        return $this->container['data_fine_sospensione'];
    }

    /**
     * Sets data_fine_sospensione
     *
     * @param string $data_fine_sospensione data_fine_sospensione
     *
     * @return $this
     */
    public function setDataFineSospensione($data_fine_sospensione)
    {
        $this->container['data_fine_sospensione'] = $data_fine_sospensione;

        return $this;
    }

    /**
     * Gets id_motivo_rinuncia
     *
     * @return int
     */
    public function getIdMotivoRinuncia()
    {
        return $this->container['id_motivo_rinuncia'];
    }

    /**
     * Sets id_motivo_rinuncia
     *
     * @param int $id_motivo_rinuncia id_motivo_rinuncia
     *
     * @return $this
     */
    public function setIdMotivoRinuncia($id_motivo_rinuncia)
    {
        $this->container['id_motivo_rinuncia'] = $id_motivo_rinuncia;

        return $this;
    }

    /**
     * Gets data_rinuncia
     *
     * @return string
     */
    public function getDataRinuncia()
    {
        return $this->container['data_rinuncia'];
    }

    /**
     * Sets data_rinuncia
     *
     * @param string $data_rinuncia data_rinuncia
     *
     * @return $this
     */
    public function setDataRinuncia($data_rinuncia)
    {
        $this->container['data_rinuncia'] = $data_rinuncia;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


